version: 2
jobs:
  build:
    docker: 
       image: circleci/ruby:2.4.1-node-browser
    
    steps:
      - checkout
      
      - run:
          name: Greetings
          commnad: echo Hello, world.
          
      - run:
          name: Prnt the Current Time
          commnad: date
