version: 2
jobs:
  build:
    docker: 
       image: circleci/ruby:2.4.1-node-browser
    
    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: bundle install
      
      - run:
          name: build the jekyll site
          commnad: bundle exec jekyll build
          
      - run:
          name: Prnt the Current Time
          commnad: date
